version: 0.2

phases:
  install:
    commands:
      - export HOME=/tmp
      - dotnet restore
  build:
    commands:
      - dotnet build -c Release
      - dotnet publish -c Release -o publish
artifacts:
  files:
    - '**/*'
  base-directory: publish